name: Notify Slack on PR

on:
  pull_request:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "{
              \"text\": \"Nova Pull Request criada por *$GITHUB_ACTOR*:\n*<$PR_URL|$PR_TITLE>*\"
            }" \
            "$SLACK_WEBHOOK_URL"